### PR TITLE
Support Version 4 API

### PR DESCRIPTION
**Pull request by cbergmann**
hi,

this is my try on implementing Version 4 of the API. It should be backward compatible in the sense that the old configuration should result in nearly the same sensors as before. There might be some differences though because I was not able to test with Version 3 because my API key is not working with that Version. 
V4 only has one endpoint for all timelines. Therefore I only used one data_provider and one sensor class. I also allow a new, more general and V4-like config format which is documented in the README.

### CODE REVIEW

**Comment by r-renato** [comment]
Thank you Clemens for your support.
Let me have time to review the changes and test the code.

Thanks, 
Renato

**Comment by r-renato** [comment]
The authentication key for api v3 does not work with api v4, so there is no backward compatibility.

**Comment by cbergmann** [comment]
Hi Renato,

I was not aware of that. I see two Strategies how we could work with that information.

1. We could try to support both versions in one integration and add a configuration flag to select the version. I suspect that this would complicate the code and that in turn would reduce maintainability.
2. Another Option would be to maintain two versions of the integration either in two branches or in two different repositories. The common code is not that big anyhow. I would volunteer trying to maintain/support the new Version. 

What is your take on this?

**Comment by cbergmann** [comment]
When we choose option 2 I would suggest changing the integration name / domain of that version from climacell to climacell_v4 or something that like to prevent naming collisions.

**Comment by r-renato** [comment]
> Hi Renato,
> 
> I was not aware of that. I see two Strategies how we could work with that information.
> 
>     1. We could try to support both versions in one integration and add a configuration flag to select the version. I suspect that this would complicate the code and that in turn would reduce maintainability.
> 
>     2. Another Option would be to maintain two versions of the integration either in two branches or in two different repositories. The common code is not that big anyhow. I would volunteer trying to maintain/support the new Version.
> 
> 
> What is your take on this?
> When we choose option 2 I would suggest changing the integration name / domain of that version from climacell to climacell_v4 or something that like to prevent naming collisions.

Climacell api v3 are deprecated and will be discontinued in the coming months. I am for a component transition, but the code needs to be stable and the documentation detailed.
If you want we can test your component changes together for a few days while we detail the documentation.

**Comment by cbergmann** [comment]
I have my code running in my HA instance. If you have any specific tests that I could try or suggestions for improvements don't hesitate to contact me.

**Comment by cbergmann** [comment]
Hi, I added the ability to prefix the field with "Raw" to disable mapping of field values.

**Comment by sircharlo** [comment]
Hey there! Great work, thank you so much
Oddly enough, I'm having the issue where the weather data loads correctly after HA starts up, but then never gets refreshed. No combination of `update` or `scan_interval` parameters seems to actually do anything; it's like the update itself is never triggered.
Am I the only one?

**Comment by cbergmann** [comment]
Hi @sircharlo,
I just checked my observation_time attribute of some of my sensors and it seems that they where just updated. Could you send us your sensor configuration (with redacted api_key, latitude and longitude).

**Comment by sircharlo** [comment]
> Hi @sircharlo,
> I just checked my observation_time attribute of some of my sensors and it seems that they where just updated. Could you send us your sensor configuration (with redacted api_key, latitude and longitude).

Sure thing. I also deleted the integration and reinstalled it from HACS using the repo `https://github.com/cbergmann/ha-climacell-weather/`, but still no change. The sensor initialize correctly on HA startup and don't get updated until the next HA restart.

Conf:

```
- platform: climacell
  api_key: !secret climacell_api_key
  monitored_conditions:
    realtime:
      conditions:
        - temperature
        - feels_like
        - precipitation
        - weather_condition
        - humidity
        - wind_speed
        - precipitation_type
        - pressure
        - visibility
        - pollen_tree
        - pollen_weed
        - pollen_grass
        - epa_health_concern
        - wind_direction
        - wind_speed
    daily:
      forecast_observations: 7
      conditions:
        - temperature
        - feels_like
#        - precipitation_accumulation
        - precipitation
        - weather_condition
#        - humidity
#        - wind_speed
        - precipitation_probability
    hourly:
      forecast_observations: 12
      conditions:
        - temperature
        - feels_like
      update: auto
      scan_interval:
        minutes: 1
```

**Comment by ScottESanDiego** [comment]
Interesting that it actually instantiates for you.  I get a failure at load time with this change.
```
2021-01-21 10:45:53 ERROR (SyncWorker_2) [custom_components.climacell.sensor] Invalid field: sunset
2021-01-21 10:45:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up climacell platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climacell/sensor.py", line 241, in setup_platform
    unit = UNITS[units][field]
KeyError: 'sunriseTime'
```

Same for `sunsetTime` and perhaps a few others.  I naively tried removing the offending items in `global_const.py` , but gave up. :-)

**Comment by cbergmann** [comment]
Hi, 
I forgot that *Time fields dont have a unit of measurement. I pushed a new version to [my branch](https://github.com/cbergmann/ha-climacell-weather). If you could test this with your configuration I will create a new pull request.

**Pull request merged**
